### ISSUE TITLE
More BT Device names

### ISSUE THREAD

**Issue by qdot** [internetofdongs/IoD-Screwdriver#1]
More names to add to the list:

"Launch" - Fleshlight Launch
"LVS_*" - Lovense (Prototype models)
"Smart Mini Vibe" - Magic Motion Smart Mini Vibe
"CycSA" - Vorze A10 Cyclone
"Youcups" - Youcups Warrior II (and probably other Youcups products)

Wevibe products:

 "4 Plus"
"Ditto"
"Nova"
"Pivot"
"Wish"
"Verge"

**Comment by internetofdongs** [comment]
Added those ones and a lot more
